/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package aufg_5.pkg1;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author Simon.Doba
 */
public class Bewegung extends javax.swing.JPanel {
 BewegungBasis[] alleBeweger = new BewegungBasis[10];
    BewegungHorizontal bH = new BewegungHorizontal();
    BewegungVertikal bV = new BewegungVertikal();
    /**
     * Creates new form Bewegung
     */
    
    public Bewegung() {
        initComponents();
         alleBeweger[0] = new BewegungHorizontal();
        alleBeweger[1] = new BewegungVertikal();
        alleBeweger[2] = new BewegungHorizontal();
        alleBeweger[3] = new BewegungVertikal();
        alleBeweger[4] = new BewegungHorizontal();
        alleBeweger[5] = new BewegungVertikal();
        alleBeweger[6] = new BewegungHorizontal();
        alleBeweger[7] = new BewegungVertikal();
        alleBeweger[8] = new BewegungHorizontal();
        alleBeweger[9] = new BewegungVertikal();
        System.out.println("Objekte init");
    }
  public void paintComponent(Graphics g){
        System.out.println("Init Paint");
       // while(true){
            g.setColor(Color.red);
        for (BewegungBasis alleBeweger1 : alleBeweger) {
            g.drawLine(bH.bewege(),bV.bewege(),200,200);
            g.setColor(Color.blue);
        }
        repaint();
        //update();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>                        

    private void formKeyReleased(java.awt.event.KeyEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void formMouseReleased(java.awt.event.MouseEvent evt) {                                   
        // TODO add your handling code here:
    }                                  


    // Variables declaration - do not modify                     
    // End of variables declaration                   
}
