package aufg_5.pkg1;

import java.awt.Graphics;

/**
 *
 * @author Simon.Doba
 */
public class BewegungGUI extends javax.swing.JFrame {
    BewegungBasis[] alleBeweger = new BewegungBasis[10];
    BewegungHorizontal bH = new BewegungHorizontal();
    BewegungVertikal bV = new BewegungVertikal();
    /**
     * Creates new form BewegungGUI
     */
    
    public BewegungGUI() {
        initComponents();
        alleBeweger[0] = new BewegungHorizontal();
        alleBeweger[1] = new BewegungVertikal();
        alleBeweger[2] = new BewegungHorizontal();
        alleBeweger[3] = new BewegungVertikal();
        alleBeweger[4] = new BewegungHorizontal();
        alleBeweger[5] = new BewegungVertikal();
        alleBeweger[6] = new BewegungHorizontal();
        alleBeweger[7] = new BewegungVertikal();
        alleBeweger[8] = new BewegungHorizontal();
        alleBeweger[9] = new BewegungVertikal();
        System.out.println("Objekte init");
    }
    public void paintComponent(Graphics g){
        System.out.println("Init Paint");
        for (BewegungBasis alleBeweger1 : alleBeweger) {
            g.drawLine(bH.bewege(),bV.bewege(),2,2);
            g.drawRect(bH.bewege(), bV.bewege(), 50, 50);
        }
        repaint();
       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        bewegung1 = new aufg_5.pkg1.Bewegung();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout bewegung1Layout = new javax.swing.GroupLayout(bewegung1);
        bewegung1.setLayout(bewegung1Layout);
        bewegung1Layout.setHorizontalGroup(
            bewegung1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 344, Short.MAX_VALUE)
        );
        bewegung1Layout.setVerticalGroup(
            bewegung1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(bewegung1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(bewegung1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BewegungGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BewegungGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BewegungGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BewegungGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BewegungGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private aufg_5.pkg1.Bewegung bewegung1;
    // End of variables declaration                   
}
